[build]
  publish = "public"
  command = "echo 'No build step required'"

[build.environment]
  GOOGLE_SHEET_ID = "true"
  GOOGLE_SERVICE_ACCOUNT = "true"
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/submit"
  to = "/.netlify/functions/submit-form"
  status = 302
  force = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
