[functions]
  node_bundler = "esbuild"
# Production-ready netlify.toml for Google Sheets form submissions

[build]
  publish = "public"            # Adjust if your site lives elsewhere
  command = "npm run build"     # Or your static build command

[build.environment]
  GOOGLE_SHEET_ID = "true"
  GOOGLE_SERVICE_ACCOUNT = "true"
  NODE_VERSION = "18"            # Recommended runtime
  SECRETS_SCAN_ENABLED = "false" # Optional: disables Netlify build failure on secret detection

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"] # Ensures all function files are bundled

[[redirects]]
  from = "/submit"
  to = "/.netlify/functions/submit-form"
  status = 302
  force = true

# Optional: Set headers for CORS or caching
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
